// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: error/v1/error.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ErrorScope with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ErrorScope) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ErrorScope with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ErrorScopeMultiError, or
// nil if none found.
func (m *ErrorScope) ValidateAll() error {
	return m.validate(true)
}

func (m *ErrorScope) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Service

	// no validation rules for Plugin

	// no validation rules for Args

	if len(errors) > 0 {
		return ErrorScopeMultiError(errors)
	}

	return nil
}

// ErrorScopeMultiError is an error wrapping multiple validation errors
// returned by ErrorScope.ValidateAll() if the designated constraints aren't met.
type ErrorScopeMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ErrorScopeMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ErrorScopeMultiError) AllErrors() []error { return m }

// ErrorScopeValidationError is the validation error returned by
// ErrorScope.Validate if the designated constraints aren't met.
type ErrorScopeValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ErrorScopeValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ErrorScopeValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ErrorScopeValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ErrorScopeValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ErrorScopeValidationError) ErrorName() string { return "ErrorScopeValidationError" }

// Error satisfies the builtin error interface
func (e ErrorScopeValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sErrorScope.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ErrorScopeValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ErrorScopeValidationError{}

// Validate checks the field values on ErrorDetails with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ErrorDetails) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ErrorDetails with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ErrorDetailsMultiError, or
// nil if none found.
func (m *ErrorDetails) ValidateAll() error {
	return m.validate(true)
}

func (m *ErrorDetails) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	// no validation rules for Cause

	if all {
		switch v := interface{}(m.GetScope()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ErrorDetailsValidationError{
					field:  "Scope",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ErrorDetailsValidationError{
					field:  "Scope",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetScope()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ErrorDetailsValidationError{
				field:  "Scope",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ErrorDetailsMultiError(errors)
	}

	return nil
}

// ErrorDetailsMultiError is an error wrapping multiple validation errors
// returned by ErrorDetails.ValidateAll() if the designated constraints aren't met.
type ErrorDetailsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ErrorDetailsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ErrorDetailsMultiError) AllErrors() []error { return m }

// ErrorDetailsValidationError is the validation error returned by
// ErrorDetails.Validate if the designated constraints aren't met.
type ErrorDetailsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ErrorDetailsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ErrorDetailsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ErrorDetailsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ErrorDetailsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ErrorDetailsValidationError) ErrorName() string { return "ErrorDetailsValidationError" }

// Error satisfies the builtin error interface
func (e ErrorDetailsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sErrorDetails.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ErrorDetailsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ErrorDetailsValidationError{}
