// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: resource/v1/resource.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on PolicyResource with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PolicyResource) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PolicyResource with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PolicyResourceMultiError,
// or nil if none found.
func (m *PolicyResource) ValidateAll() error {
	return m.validate(true)
}

func (m *PolicyResource) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetPrincipals() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, PolicyResourceValidationError{
						field:  fmt.Sprintf("Principals[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, PolicyResourceValidationError{
						field:  fmt.Sprintf("Principals[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return PolicyResourceValidationError{
					field:  fmt.Sprintf("Principals[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetResources() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, PolicyResourceValidationError{
						field:  fmt.Sprintf("Resources[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, PolicyResourceValidationError{
						field:  fmt.Sprintf("Resources[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return PolicyResourceValidationError{
					field:  fmt.Sprintf("Resources[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return PolicyResourceMultiError(errors)
	}

	return nil
}

// PolicyResourceMultiError is an error wrapping multiple validation errors
// returned by PolicyResource.ValidateAll() if the designated constraints
// aren't met.
type PolicyResourceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PolicyResourceMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PolicyResourceMultiError) AllErrors() []error { return m }

// PolicyResourceValidationError is the validation error returned by
// PolicyResource.Validate if the designated constraints aren't met.
type PolicyResourceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PolicyResourceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PolicyResourceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PolicyResourceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PolicyResourceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PolicyResourceValidationError) ErrorName() string { return "PolicyResourceValidationError" }

// Error satisfies the builtin error interface
func (e PolicyResourceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPolicyResource.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PolicyResourceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PolicyResourceValidationError{}

// Validate checks the field values on Resource with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Resource) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Resource with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ResourceMultiError, or nil
// if none found.
func (m *Resource) ValidateAll() error {
	return m.validate(true)
}

func (m *Resource) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Type

	// no validation rules for Name

	if len(errors) > 0 {
		return ResourceMultiError(errors)
	}

	return nil
}

// ResourceMultiError is an error wrapping multiple validation errors returned
// by Resource.ValidateAll() if the designated constraints aren't met.
type ResourceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResourceMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResourceMultiError) AllErrors() []error { return m }

// ResourceValidationError is the validation error returned by
// Resource.Validate if the designated constraints aren't met.
type ResourceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResourceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResourceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResourceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResourceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResourceValidationError) ErrorName() string { return "ResourceValidationError" }

// Error satisfies the builtin error interface
func (e ResourceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResource.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResourceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResourceValidationError{}

// Validate checks the field values on ResourceDeclareRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ResourceDeclareRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ResourceDeclareRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ResourceDeclareRequestMultiError, or nil if none found.
func (m *ResourceDeclareRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ResourceDeclareRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetResource()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ResourceDeclareRequestValidationError{
					field:  "Resource",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ResourceDeclareRequestValidationError{
					field:  "Resource",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetResource()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ResourceDeclareRequestValidationError{
				field:  "Resource",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	switch m.Config.(type) {

	case *ResourceDeclareRequest_Policy:

		if all {
			switch v := interface{}(m.GetPolicy()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ResourceDeclareRequestValidationError{
						field:  "Policy",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ResourceDeclareRequestValidationError{
						field:  "Policy",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetPolicy()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ResourceDeclareRequestValidationError{
					field:  "Policy",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *ResourceDeclareRequest_Bucket:

		if all {
			switch v := interface{}(m.GetBucket()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ResourceDeclareRequestValidationError{
						field:  "Bucket",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ResourceDeclareRequestValidationError{
						field:  "Bucket",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetBucket()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ResourceDeclareRequestValidationError{
					field:  "Bucket",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *ResourceDeclareRequest_Queue:

		if all {
			switch v := interface{}(m.GetQueue()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ResourceDeclareRequestValidationError{
						field:  "Queue",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ResourceDeclareRequestValidationError{
						field:  "Queue",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetQueue()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ResourceDeclareRequestValidationError{
					field:  "Queue",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *ResourceDeclareRequest_Topic:

		if all {
			switch v := interface{}(m.GetTopic()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ResourceDeclareRequestValidationError{
						field:  "Topic",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ResourceDeclareRequestValidationError{
						field:  "Topic",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetTopic()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ResourceDeclareRequestValidationError{
					field:  "Topic",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *ResourceDeclareRequest_Collection:

		if all {
			switch v := interface{}(m.GetCollection()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ResourceDeclareRequestValidationError{
						field:  "Collection",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ResourceDeclareRequestValidationError{
						field:  "Collection",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetCollection()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ResourceDeclareRequestValidationError{
					field:  "Collection",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *ResourceDeclareRequest_Secret:

		if all {
			switch v := interface{}(m.GetSecret()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ResourceDeclareRequestValidationError{
						field:  "Secret",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ResourceDeclareRequestValidationError{
						field:  "Secret",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetSecret()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ResourceDeclareRequestValidationError{
					field:  "Secret",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *ResourceDeclareRequest_Api:

		if all {
			switch v := interface{}(m.GetApi()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ResourceDeclareRequestValidationError{
						field:  "Api",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ResourceDeclareRequestValidationError{
						field:  "Api",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetApi()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ResourceDeclareRequestValidationError{
					field:  "Api",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *ResourceDeclareRequest_DeadLetter:

		if all {
			switch v := interface{}(m.GetDeadLetter()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ResourceDeclareRequestValidationError{
						field:  "DeadLetter",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ResourceDeclareRequestValidationError{
						field:  "DeadLetter",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetDeadLetter()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ResourceDeclareRequestValidationError{
					field:  "DeadLetter",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ResourceDeclareRequestMultiError(errors)
	}

	return nil
}

// ResourceDeclareRequestMultiError is an error wrapping multiple validation
// errors returned by ResourceDeclareRequest.ValidateAll() if the designated
// constraints aren't met.
type ResourceDeclareRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResourceDeclareRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResourceDeclareRequestMultiError) AllErrors() []error { return m }

// ResourceDeclareRequestValidationError is the validation error returned by
// ResourceDeclareRequest.Validate if the designated constraints aren't met.
type ResourceDeclareRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResourceDeclareRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResourceDeclareRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResourceDeclareRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResourceDeclareRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResourceDeclareRequestValidationError) ErrorName() string {
	return "ResourceDeclareRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ResourceDeclareRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResourceDeclareRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResourceDeclareRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResourceDeclareRequestValidationError{}

// Validate checks the field values on BucketResource with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *BucketResource) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BucketResource with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in BucketResourceMultiError,
// or nil if none found.
func (m *BucketResource) ValidateAll() error {
	return m.validate(true)
}

func (m *BucketResource) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return BucketResourceMultiError(errors)
	}

	return nil
}

// BucketResourceMultiError is an error wrapping multiple validation errors
// returned by BucketResource.ValidateAll() if the designated constraints
// aren't met.
type BucketResourceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BucketResourceMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BucketResourceMultiError) AllErrors() []error { return m }

// BucketResourceValidationError is the validation error returned by
// BucketResource.Validate if the designated constraints aren't met.
type BucketResourceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BucketResourceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BucketResourceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BucketResourceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BucketResourceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BucketResourceValidationError) ErrorName() string { return "BucketResourceValidationError" }

// Error satisfies the builtin error interface
func (e BucketResourceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBucketResource.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BucketResourceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BucketResourceValidationError{}

// Validate checks the field values on QueueResource with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *QueueResource) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QueueResource with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in QueueResourceMultiError, or
// nil if none found.
func (m *QueueResource) ValidateAll() error {
	return m.validate(true)
}

func (m *QueueResource) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return QueueResourceMultiError(errors)
	}

	return nil
}

// QueueResourceMultiError is an error wrapping multiple validation errors
// returned by QueueResource.ValidateAll() if the designated constraints
// aren't met.
type QueueResourceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QueueResourceMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QueueResourceMultiError) AllErrors() []error { return m }

// QueueResourceValidationError is the validation error returned by
// QueueResource.Validate if the designated constraints aren't met.
type QueueResourceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueueResourceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueueResourceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueueResourceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueueResourceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueueResourceValidationError) ErrorName() string { return "QueueResourceValidationError" }

// Error satisfies the builtin error interface
func (e QueueResourceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQueueResource.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueueResourceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueueResourceValidationError{}

// Validate checks the field values on TopicResource with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TopicResource) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TopicResource with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TopicResourceMultiError, or
// nil if none found.
func (m *TopicResource) ValidateAll() error {
	return m.validate(true)
}

func (m *TopicResource) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return TopicResourceMultiError(errors)
	}

	return nil
}

// TopicResourceMultiError is an error wrapping multiple validation errors
// returned by TopicResource.ValidateAll() if the designated constraints
// aren't met.
type TopicResourceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TopicResourceMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TopicResourceMultiError) AllErrors() []error { return m }

// TopicResourceValidationError is the validation error returned by
// TopicResource.Validate if the designated constraints aren't met.
type TopicResourceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TopicResourceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TopicResourceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TopicResourceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TopicResourceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TopicResourceValidationError) ErrorName() string { return "TopicResourceValidationError" }

// Error satisfies the builtin error interface
func (e TopicResourceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTopicResource.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TopicResourceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TopicResourceValidationError{}

// Validate checks the field values on CollectionResource with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CollectionResource) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CollectionResource with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CollectionResourceMultiError, or nil if none found.
func (m *CollectionResource) ValidateAll() error {
	return m.validate(true)
}

func (m *CollectionResource) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return CollectionResourceMultiError(errors)
	}

	return nil
}

// CollectionResourceMultiError is an error wrapping multiple validation errors
// returned by CollectionResource.ValidateAll() if the designated constraints
// aren't met.
type CollectionResourceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CollectionResourceMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CollectionResourceMultiError) AllErrors() []error { return m }

// CollectionResourceValidationError is the validation error returned by
// CollectionResource.Validate if the designated constraints aren't met.
type CollectionResourceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CollectionResourceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CollectionResourceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CollectionResourceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CollectionResourceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CollectionResourceValidationError) ErrorName() string {
	return "CollectionResourceValidationError"
}

// Error satisfies the builtin error interface
func (e CollectionResourceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCollectionResource.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CollectionResourceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CollectionResourceValidationError{}

// Validate checks the field values on SecretResource with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SecretResource) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SecretResource with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SecretResourceMultiError,
// or nil if none found.
func (m *SecretResource) ValidateAll() error {
	return m.validate(true)
}

func (m *SecretResource) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return SecretResourceMultiError(errors)
	}

	return nil
}

// SecretResourceMultiError is an error wrapping multiple validation errors
// returned by SecretResource.ValidateAll() if the designated constraints
// aren't met.
type SecretResourceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SecretResourceMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SecretResourceMultiError) AllErrors() []error { return m }

// SecretResourceValidationError is the validation error returned by
// SecretResource.Validate if the designated constraints aren't met.
type SecretResourceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SecretResourceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SecretResourceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SecretResourceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SecretResourceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SecretResourceValidationError) ErrorName() string { return "SecretResourceValidationError" }

// Error satisfies the builtin error interface
func (e SecretResourceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSecretResource.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SecretResourceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SecretResourceValidationError{}

// Validate checks the field values on DeadLetterResource with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeadLetterResource) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeadLetterResource with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeadLetterResourceMultiError, or nil if none found.
func (m *DeadLetterResource) ValidateAll() error {
	return m.validate(true)
}

func (m *DeadLetterResource) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeadLetterResourceMultiError(errors)
	}

	return nil
}

// DeadLetterResourceMultiError is an error wrapping multiple validation errors
// returned by DeadLetterResource.ValidateAll() if the designated constraints
// aren't met.
type DeadLetterResourceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeadLetterResourceMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeadLetterResourceMultiError) AllErrors() []error { return m }

// DeadLetterResourceValidationError is the validation error returned by
// DeadLetterResource.Validate if the designated constraints aren't met.
type DeadLetterResourceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeadLetterResourceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeadLetterResourceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeadLetterResourceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeadLetterResourceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeadLetterResourceValidationError) ErrorName() string {
	return "DeadLetterResourceValidationError"
}

// Error satisfies the builtin error interface
func (e DeadLetterResourceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeadLetterResource.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeadLetterResourceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeadLetterResourceValidationError{}

// Validate checks the field values on ApiSecurityDefinitionJwt with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ApiSecurityDefinitionJwt) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ApiSecurityDefinitionJwt with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ApiSecurityDefinitionJwtMultiError, or nil if none found.
func (m *ApiSecurityDefinitionJwt) ValidateAll() error {
	return m.validate(true)
}

func (m *ApiSecurityDefinitionJwt) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Issuer

	if len(errors) > 0 {
		return ApiSecurityDefinitionJwtMultiError(errors)
	}

	return nil
}

// ApiSecurityDefinitionJwtMultiError is an error wrapping multiple validation
// errors returned by ApiSecurityDefinitionJwt.ValidateAll() if the designated
// constraints aren't met.
type ApiSecurityDefinitionJwtMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ApiSecurityDefinitionJwtMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ApiSecurityDefinitionJwtMultiError) AllErrors() []error { return m }

// ApiSecurityDefinitionJwtValidationError is the validation error returned by
// ApiSecurityDefinitionJwt.Validate if the designated constraints aren't met.
type ApiSecurityDefinitionJwtValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ApiSecurityDefinitionJwtValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ApiSecurityDefinitionJwtValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ApiSecurityDefinitionJwtValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ApiSecurityDefinitionJwtValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ApiSecurityDefinitionJwtValidationError) ErrorName() string {
	return "ApiSecurityDefinitionJwtValidationError"
}

// Error satisfies the builtin error interface
func (e ApiSecurityDefinitionJwtValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sApiSecurityDefinitionJwt.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ApiSecurityDefinitionJwtValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ApiSecurityDefinitionJwtValidationError{}

// Validate checks the field values on ApiSecurityDefinition with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ApiSecurityDefinition) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ApiSecurityDefinition with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ApiSecurityDefinitionMultiError, or nil if none found.
func (m *ApiSecurityDefinition) ValidateAll() error {
	return m.validate(true)
}

func (m *ApiSecurityDefinition) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	switch m.Definition.(type) {

	case *ApiSecurityDefinition_Jwt:

		if all {
			switch v := interface{}(m.GetJwt()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ApiSecurityDefinitionValidationError{
						field:  "Jwt",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ApiSecurityDefinitionValidationError{
						field:  "Jwt",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetJwt()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ApiSecurityDefinitionValidationError{
					field:  "Jwt",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ApiSecurityDefinitionMultiError(errors)
	}

	return nil
}

// ApiSecurityDefinitionMultiError is an error wrapping multiple validation
// errors returned by ApiSecurityDefinition.ValidateAll() if the designated
// constraints aren't met.
type ApiSecurityDefinitionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ApiSecurityDefinitionMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ApiSecurityDefinitionMultiError) AllErrors() []error { return m }

// ApiSecurityDefinitionValidationError is the validation error returned by
// ApiSecurityDefinition.Validate if the designated constraints aren't met.
type ApiSecurityDefinitionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ApiSecurityDefinitionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ApiSecurityDefinitionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ApiSecurityDefinitionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ApiSecurityDefinitionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ApiSecurityDefinitionValidationError) ErrorName() string {
	return "ApiSecurityDefinitionValidationError"
}

// Error satisfies the builtin error interface
func (e ApiSecurityDefinitionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sApiSecurityDefinition.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ApiSecurityDefinitionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ApiSecurityDefinitionValidationError{}

// Validate checks the field values on ApiScopes with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ApiScopes) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ApiScopes with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ApiScopesMultiError, or nil
// if none found.
func (m *ApiScopes) ValidateAll() error {
	return m.validate(true)
}

func (m *ApiScopes) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ApiScopesMultiError(errors)
	}

	return nil
}

// ApiScopesMultiError is an error wrapping multiple validation errors returned
// by ApiScopes.ValidateAll() if the designated constraints aren't met.
type ApiScopesMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ApiScopesMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ApiScopesMultiError) AllErrors() []error { return m }

// ApiScopesValidationError is the validation error returned by
// ApiScopes.Validate if the designated constraints aren't met.
type ApiScopesValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ApiScopesValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ApiScopesValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ApiScopesValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ApiScopesValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ApiScopesValidationError) ErrorName() string { return "ApiScopesValidationError" }

// Error satisfies the builtin error interface
func (e ApiScopesValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sApiScopes.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ApiScopesValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ApiScopesValidationError{}

// Validate checks the field values on ApiResource with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ApiResource) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ApiResource with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ApiResourceMultiError, or
// nil if none found.
func (m *ApiResource) ValidateAll() error {
	return m.validate(true)
}

func (m *ApiResource) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	{
		sorted_keys := make([]string, len(m.GetSecurityDefinitions()))
		i := 0
		for key := range m.GetSecurityDefinitions() {
			sorted_keys[i] = key
			i++
		}
		sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
		for _, key := range sorted_keys {
			val := m.GetSecurityDefinitions()[key]
			_ = val

			// no validation rules for SecurityDefinitions[key]

			if all {
				switch v := interface{}(val).(type) {
				case interface{ ValidateAll() error }:
					if err := v.ValidateAll(); err != nil {
						errors = append(errors, ApiResourceValidationError{
							field:  fmt.Sprintf("SecurityDefinitions[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				case interface{ Validate() error }:
					if err := v.Validate(); err != nil {
						errors = append(errors, ApiResourceValidationError{
							field:  fmt.Sprintf("SecurityDefinitions[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				}
			} else if v, ok := interface{}(val).(interface{ Validate() error }); ok {
				if err := v.Validate(); err != nil {
					return ApiResourceValidationError{
						field:  fmt.Sprintf("SecurityDefinitions[%v]", key),
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		}
	}

	{
		sorted_keys := make([]string, len(m.GetSecurity()))
		i := 0
		for key := range m.GetSecurity() {
			sorted_keys[i] = key
			i++
		}
		sort.Slice(sorted_keys, func(i, j int) bool { return sorted_keys[i] < sorted_keys[j] })
		for _, key := range sorted_keys {
			val := m.GetSecurity()[key]
			_ = val

			// no validation rules for Security[key]

			if all {
				switch v := interface{}(val).(type) {
				case interface{ ValidateAll() error }:
					if err := v.ValidateAll(); err != nil {
						errors = append(errors, ApiResourceValidationError{
							field:  fmt.Sprintf("Security[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				case interface{ Validate() error }:
					if err := v.Validate(); err != nil {
						errors = append(errors, ApiResourceValidationError{
							field:  fmt.Sprintf("Security[%v]", key),
							reason: "embedded message failed validation",
							cause:  err,
						})
					}
				}
			} else if v, ok := interface{}(val).(interface{ Validate() error }); ok {
				if err := v.Validate(); err != nil {
					return ApiResourceValidationError{
						field:  fmt.Sprintf("Security[%v]", key),
						reason: "embedded message failed validation",
						cause:  err,
					}
				}
			}

		}
	}

	if len(errors) > 0 {
		return ApiResourceMultiError(errors)
	}

	return nil
}

// ApiResourceMultiError is an error wrapping multiple validation errors
// returned by ApiResource.ValidateAll() if the designated constraints aren't met.
type ApiResourceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ApiResourceMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ApiResourceMultiError) AllErrors() []error { return m }

// ApiResourceValidationError is the validation error returned by
// ApiResource.Validate if the designated constraints aren't met.
type ApiResourceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ApiResourceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ApiResourceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ApiResourceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ApiResourceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ApiResourceValidationError) ErrorName() string { return "ApiResourceValidationError" }

// Error satisfies the builtin error interface
func (e ApiResourceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sApiResource.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ApiResourceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ApiResourceValidationError{}

// Validate checks the field values on ResourceDeclareResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ResourceDeclareResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ResourceDeclareResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ResourceDeclareResponseMultiError, or nil if none found.
func (m *ResourceDeclareResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ResourceDeclareResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ResourceDeclareResponseMultiError(errors)
	}

	return nil
}

// ResourceDeclareResponseMultiError is an error wrapping multiple validation
// errors returned by ResourceDeclareResponse.ValidateAll() if the designated
// constraints aren't met.
type ResourceDeclareResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResourceDeclareResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResourceDeclareResponseMultiError) AllErrors() []error { return m }

// ResourceDeclareResponseValidationError is the validation error returned by
// ResourceDeclareResponse.Validate if the designated constraints aren't met.
type ResourceDeclareResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResourceDeclareResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResourceDeclareResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResourceDeclareResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResourceDeclareResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResourceDeclareResponseValidationError) ErrorName() string {
	return "ResourceDeclareResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ResourceDeclareResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResourceDeclareResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResourceDeclareResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResourceDeclareResponseValidationError{}
